### PR TITLE
Stackify the eval function

### PR DESCRIPTION
**Pull request by TyOverby**
@bwo 
## This commit removes all recursion from the eval/apply loop.

(except for ForeignFn calls)
(at the cost of making it much much more complicated)
### Why

When the interpreter was recursive, it was really simple conceptually, but left a lot to be desired.  With native-recursion, these problems existed:
- Hard to get a stack trace
- Impossible to implement continuations
- Impossible to implement common debugger features
- Impossible to "snapshot" the running VM, saving it for later
- Hard to implement exception handling 
### How

Basically by turning the eval stack into a stack of state machines.  Where recursion would naturally occur, the stack is grown (just like the OS callstack)

The `step_eval` function runs one "tick" of the interpreter.  `eval` just calls `step_eval` until it's done.
### From Here

Right now this commit doesn't really accomplish much, because all the core functions are implemented as `user_fn` or `ast_fn` which means that they **do** end up recursively calling `eval` as they execute. 

After this gets merged, I'll start porting all the `core`, `arithmetic` and `logical` modules to be actually built into the interpreter core.
### Example

A good example of the "state machine" design is how lambdas are handled.  A "call" starts out putting both of these on the stack 

```
# Bottom of the stack
PreEvaluatedCallable { unevaluated: [arg_ast_1, arg_ast_2] } # All the unevaluated arguments
EvalThis(unevaluated_function)                               # Evaluate the "function" 
# Top of the stack
```

Which turns into 

```
# Bottom of the stack
PreEvaluatedCallable { unevaluated: [arg_ast_1, arg_ast_2] }   # All the unevaluated arguments
Complete(func)                                                 # Evaluate the "function" 
# Top of the stack
```

Which turns into 

```
# Bottom of the stack
ArgCollectingLambda { func: func, evaluated: [], unevaluated: [arg_ast_2] } # Collecting arguments
EvalThis(arg_ast_1)
# Top of the stack
```

Which turns into 

```
# Bottom of the stack
ArgCollectingLambda { func: func, evaluated: [], unevaluated: [arg_ast_2] } # Collecting arguments
Complete(arg_complete_1)
# Top of the stack
```

Which turns into 

```
# Bottom of the stack
ArgCollectingLambda { func: func, evaluated: [arg_complete_1], unevaluated: [] } # Collecting arguments
EvalThis(arg_ast_2)
# Top of the stack
```

Which turns into 

```
# Bottom of the stack
ArgCollectingLambda { func: func, evaluated: [arg_complete_1], unevaluated: [] } # Collecting arguments
Complete(arg_complete_2)
# Top of the stack
```

Which turns into 

```
# Bottom of the stack
ArgCollectingLambda { func: func, evaluated: [arg_complete_1, arg_complete_2], unevaluated: [] } # Collecting arguments
# Top of the stack
```

At which point, `func` is called with the evaluated arguments.

All the commits in this PR build and pass tests, so you can see how things evolved over the last two days.

### CODE REVIEW

**Comment by TyOverby** [comment]
@bwo 

I added comments in the 2nd to last commit, but the commits are fairly linear in how they add features.  

Also, I couldn't get the Macros integration test working.  Could you take a look at that?

**Comment by bwo** [comment]
will do, will likely have to wait a bit though

**Comment by TyOverby** [comment]
No problem.  If you want to quickly review this pull, we could merge sooner, and work on fixing macros eventually?

**Comment by bwo** [comment]
looks good to me, the one comment I have is that the subtraction by two in `cleanup_stack` seems kind of like a magic constant in context, maybe makes more sense to pass in a desired stack size and pop until that's reached.

**Comment by TyOverby** [comment]
That sounds like a good change.  I'll fix it and then merge later tonight.

**Comment by TyOverby** [comment]
Merged! :tada:

**Comment by bwo** [comment]
The repl example is also busted---`let` is failing.

```
repl> (let (x 1) x)
UndefinedName("x")
repl> ^Z
```

Adding this test to `basic_let` leads to it failing too:

```
    eval_ok!("((lambda (z) (let (x 1) (- x z))) 0)", 1);
```

Also with an UndefinedName("x").

**Pull request merged**
